//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { UsersEntity } from './db/Users.entity';
import { CustomersEntity } from './db/Customers.entity';
import { WorkoutsEntity } from './db/Workouts.entity';
import { NutritionEntity } from './db/Nutrition.entity';
import { HealthMetricsEntity } from './db/HealthMetrics.entity';
import { NotificationsEntity } from './db/Notifications.entity';
import { SupportTicketsEntity } from './db/SupportTickets.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      UsersEntity,
      CustomersEntity,
      WorkoutsEntity,
      NutritionEntity,
      HealthMetricsEntity,
      NotificationsEntity,
      SupportTicketsEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Users: [
        {
          userId: 1,
          name: 'name 1',
          email: 'email 1',
          password: 'password 1',
          role: 'role 1',
          id: 33,
        },
        {
          userId: 2,
          name: 'name 2',
          email: 'email 2',
          password: 'password 2',
          role: 'role 2',
          id: 60,
        },
        {
          userId: 3,
          name: 'name 3',
          email: 'email 3',
          password: 'password 3',
          role: 'role 3',
          id: 72,
        },
        {
          userId: 4,
          name: 'name 4',
          email: 'email 4',
          password: 'password 4',
          role: 'role 4',
          id: 4,
        },
        {
          userId: 5,
          name: 'name 5',
          email: 'email 5',
          password: 'password 5',
          role: 'role 5',
          id: 27,
        },
      ],
      Customers: [
        {
          customerId: 1,
          email: 'email 1',
          password: 'password 1',
          name: 'name 1',
          age: 1,
          gender: 'gender 1',
          weight: 0.43,
          height: 0.36,
          healthConditions: 'healthConditions 1',
          goals: 'goals 1',
          dietaryPreferences: 'dietaryPreferences 1',
          billingAddress: 'billingAddress 1',
          country: 'country 1',
          phone: 'phone 1',
          id: 30,
        },
        {
          customerId: 2,
          email: 'email 2',
          password: 'password 2',
          name: 'name 2',
          age: 2,
          gender: 'gender 2',
          weight: 0.66,
          height: 0.55,
          healthConditions: 'healthConditions 2',
          goals: 'goals 2',
          dietaryPreferences: 'dietaryPreferences 2',
          billingAddress: 'billingAddress 2',
          country: 'country 2',
          phone: 'phone 2',
          id: 84,
        },
        {
          customerId: 3,
          email: 'email 3',
          password: 'password 3',
          name: 'name 3',
          age: 3,
          gender: 'gender 3',
          weight: 0.08,
          height: 0.87,
          healthConditions: 'healthConditions 3',
          goals: 'goals 3',
          dietaryPreferences: 'dietaryPreferences 3',
          billingAddress: 'billingAddress 3',
          country: 'country 3',
          phone: 'phone 3',
          id: 6,
        },
        {
          customerId: 4,
          email: 'email 4',
          password: 'password 4',
          name: 'name 4',
          age: 4,
          gender: 'gender 4',
          weight: 0.45,
          height: 0.74,
          healthConditions: 'healthConditions 4',
          goals: 'goals 4',
          dietaryPreferences: 'dietaryPreferences 4',
          billingAddress: 'billingAddress 4',
          country: 'country 4',
          phone: 'phone 4',
          id: 24,
        },
        {
          customerId: 5,
          email: 'email 5',
          password: 'password 5',
          name: 'name 5',
          age: 5,
          gender: 'gender 5',
          weight: 0.34,
          height: 0.42,
          healthConditions: 'healthConditions 5',
          goals: 'goals 5',
          dietaryPreferences: 'dietaryPreferences 5',
          billingAddress: 'billingAddress 5',
          country: 'country 5',
          phone: 'phone 5',
          id: 47,
        },
      ],
      Workouts: [
        {
          workoutId: 1,
          customerId: 1,
          type: 'type 1',
          duration: 0.36,
          intensity: 'intensity 1',
          caloriesBurned: 0.49,
          date: '2024-04-13T03:15:52.019Z',
          id: 28,
        },
        {
          workoutId: 2,
          customerId: 2,
          type: 'type 2',
          duration: 0.23,
          intensity: 'intensity 2',
          caloriesBurned: 0.07,
          date: '2024-06-26T02:47:35.106Z',
          id: 100,
        },
        {
          workoutId: 3,
          customerId: 3,
          type: 'type 3',
          duration: 0.27,
          intensity: 'intensity 3',
          caloriesBurned: 0.11,
          date: '2025-04-10T03:01:27.648Z',
          id: 13,
        },
        {
          workoutId: 4,
          customerId: 4,
          type: 'type 4',
          duration: 0.73,
          intensity: 'intensity 4',
          caloriesBurned: 0.54,
          date: '2023-09-07T04:02:27.544Z',
          id: 23,
        },
        {
          workoutId: 5,
          customerId: 5,
          type: 'type 5',
          duration: 0.9,
          intensity: 'intensity 5',
          caloriesBurned: 0.89,
          date: '2024-11-10T19:03:12.879Z',
          id: 6,
        },
      ],
      Nutrition: [
        {
          mealId: 1,
          customerId: 1,
          foodItem: 'foodItem 1',
          quantity: 0.2,
          calories: 0.82,
          macronutrients: 'macronutrients 1',
          date: '2024-10-19T18:52:05.714Z',
          id: 72,
        },
        {
          mealId: 2,
          customerId: 2,
          foodItem: 'foodItem 2',
          quantity: 0.8,
          calories: 0.28,
          macronutrients: 'macronutrients 2',
          date: '2024-07-06T04:06:54.905Z',
          id: 4,
        },
        {
          mealId: 3,
          customerId: 3,
          foodItem: 'foodItem 3',
          quantity: 0.93,
          calories: 0.31,
          macronutrients: 'macronutrients 3',
          date: '2023-10-28T15:08:10.075Z',
          id: 81,
        },
        {
          mealId: 4,
          customerId: 4,
          foodItem: 'foodItem 4',
          quantity: 0.07,
          calories: 0.9,
          macronutrients: 'macronutrients 4',
          date: '2023-11-09T01:39:02.531Z',
          id: 18,
        },
        {
          mealId: 5,
          customerId: 5,
          foodItem: 'foodItem 5',
          quantity: 0.84,
          calories: 0.56,
          macronutrients: 'macronutrients 5',
          date: '2024-03-13T10:42:50.117Z',
          id: 84,
        },
      ],
      HealthMetrics: [
        {
          metricId: 1,
          customerId: 1,
          type: 'type 1',
          value: 0.17,
          unit: 'unit 1',
          date: '2024-11-03T06:12:06.959Z',
          id: 96,
        },
        {
          metricId: 2,
          customerId: 2,
          type: 'type 2',
          value: 0.05,
          unit: 'unit 2',
          date: '2025-04-07T18:34:57.986Z',
          id: 83,
        },
        {
          metricId: 3,
          customerId: 3,
          type: 'type 3',
          value: 0.86,
          unit: 'unit 3',
          date: '2024-06-06T23:52:23.222Z',
          id: 60,
        },
        {
          metricId: 4,
          customerId: 4,
          type: 'type 4',
          value: 0.03,
          unit: 'unit 4',
          date: '2024-12-05T02:13:03.396Z',
          id: 62,
        },
        {
          metricId: 5,
          customerId: 5,
          type: 'type 5',
          value: 0.75,
          unit: 'unit 5',
          date: '2023-07-13T16:12:58.354Z',
          id: 14,
        },
      ],
      Notifications: [
        {
          notificationId: 1,
          customerId: 1,
          type: 'type 1',
          message: 'message 1',
          dateScheduled: '2024-05-02T10:11:29.159Z',
          status: 'status 1',
          id: 45,
        },
        {
          notificationId: 2,
          customerId: 2,
          type: 'type 2',
          message: 'message 2',
          dateScheduled: '2023-10-20T07:28:57.765Z',
          status: 'status 2',
          id: 17,
        },
        {
          notificationId: 3,
          customerId: 3,
          type: 'type 3',
          message: 'message 3',
          dateScheduled: '2023-06-06T16:02:44.403Z',
          status: 'status 3',
          id: 74,
        },
        {
          notificationId: 4,
          customerId: 4,
          type: 'type 4',
          message: 'message 4',
          dateScheduled: '2023-11-03T09:56:44.011Z',
          status: 'status 4',
          id: 41,
        },
        {
          notificationId: 5,
          customerId: 5,
          type: 'type 5',
          message: 'message 5',
          dateScheduled: '2023-10-25T14:27:22.400Z',
          status: 'status 5',
          id: 0,
        },
      ],
      SupportTickets: [
        {
          ticketId: 1,
          userId: 1,
          customerId: 1,
          description: 'description 1',
          status: 'status 1',
          creationDate: '2023-09-02T05:26:07.661Z',
          resolutionDate: '2023-08-20T03:01:56.246Z',
          id: 24,
        },
        {
          ticketId: 2,
          userId: 2,
          customerId: 2,
          description: 'description 2',
          status: 'status 2',
          creationDate: '2024-06-26T04:20:04.852Z',
          resolutionDate: '2024-01-02T11:17:28.834Z',
          id: 47,
        },
        {
          ticketId: 3,
          userId: 3,
          customerId: 3,
          description: 'description 3',
          status: 'status 3',
          creationDate: '2024-05-27T09:43:32.854Z',
          resolutionDate: '2024-10-25T04:31:46.461Z',
          id: 40,
        },
        {
          ticketId: 4,
          userId: 4,
          customerId: 4,
          description: 'description 4',
          status: 'status 4',
          creationDate: '2024-10-22T23:59:52.873Z',
          resolutionDate: '2024-09-05T09:22:50.301Z',
          id: 90,
        },
        {
          ticketId: 5,
          userId: 5,
          customerId: 5,
          description: 'description 5',
          status: 'status 5',
          creationDate: '2024-03-15T14:17:05.732Z',
          resolutionDate: '2025-02-02T16:22:49.107Z',
          id: 38,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('UsersEntity', data.Users);
      await this.SeedResource('CustomersEntity', data.Customers);
      await this.SeedResource('WorkoutsEntity', data.Workouts);
      await this.SeedResource('NutritionEntity', data.Nutrition);
      await this.SeedResource('HealthMetricsEntity', data.HealthMetrics);
      await this.SeedResource('NotificationsEntity', data.Notifications);
      await this.SeedResource('SupportTicketsEntity', data.SupportTickets);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
